version: "3"
services:
  mongodb:
    image: mongo:5.0
    ports:
      - 27017:27017
    volumes:
      - ~/apps/mongo:/data/db
    environment:
      - MONGO_ROOT_USERNAME=benola
      - MONGO_ROOT_PASSWORD=Su0p3rs3cr3t